spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123

  session:
    store-type: none

server:
  port: 8060

#security:
#  basic:
#    enabled: false

#imooc:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
imooc:
  security:
    browser:
      loginType: REDIRECT
